### PR TITLE
Add Track Changes feature for peer assessments

### PR DESCRIPTION
**Pull request by kluo**
We've been using this feature on our instance for several years and it works well.
* Creates "TrackChanges" django model, which ties a (submission_uuid,
  scorer_id) pair to a set of edits suggested by peers for a particular
  submission.
* Adds machinery for on-the-fly installation of the New York Times's ICE
  library for collaborative editing, allowing peer assessors to create
  marked-up versions of submissions, which can then be returned to the
  author as feedback.
* Adds machinery for displaying suggested edits to the creator of a
  submission with their scores and other feedback.
* Configurable within Studio on a per-Assessment basis by toggling the
  "Enable Track Changes" setting.

#### Enabling in studio:
Screen Shot 2019-09-04 at 11 15 21 AM

#### Student assess view:
Screen Shot 2019-09-04 at 11 23 02 AM

#### Student grade view:
Screen Shot 2019-09-04 at 11 27 46 AM

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kluo! I've created [OSPR-3814](https://openedx.atlassian.net/browse/OSPR-3814) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@kluo Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by kluo** [comment]
@natabene It's ready for review :)

**Comment by natabene** [comment]
@ormsbee Can you give this a look?

**Comment by natabene** [comment]
@marcotuts I think you should take a look before Dave.

**Comment by marcotuts** [comment]
Thanks for including screenshots here! I will work with a team internally to review on a sandbox next.

**Comment by natabene** [comment]
@marcotuts @sapanathomas523 Is product still interested in this?

**Comment by mattcarter** [comment]
@natabene - talked with @sapanathomas523 and she's interested in the feature.  We'll see about a review and cleaning up the merge conflicts.

**Comment by natabene** [comment]
@mattcarter Thank you for an update! Any idea about timeline for review - this sprint or next?

**Comment by jnlapierre** [comment]
Good Afternoon :) I've been asked to review this PR.  If it is still relevant, may I ask that conflicts be resolved and I will review?

**Comment by e0d** [comment]
@kluo I don't have a lot of context on this PR.  Is this something you still have time and interest in pushing forward?

@marcotuts Is this on your radar?

**Comment by natabene** [comment]
@e0d I believe the author is no longer around or interest. Product [seemed](https://github.com/edx/edx-ora2/pull/1258#issuecomment-759642864) to be interested, so we if we want this, we would need to do it ourselves.

**Comment by ProductRyan** [comment]
Hello. I'm the new Product Manager for this area. Apologies on the slow responses over time.

@kluo - are you still interested in implementing and supporting this functionality? We (2U/edX) are unable to support this functionality as we are focused on other aspects of grading for the foreseeable future.

**Comment by ProductRyan** [comment]
@natabene can you close this PR please?

**Comment by openedx-webhooks** [comment]
@kluo Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-ora2&entry.867055334=https://github.com/openedx/edx-ora2/pull/1258&entry.1484655318=https://github.com/kluo&entry.752974735=2019-08-29+18:52&entry.1917517419=2022-08-26+15:45&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
