### PR TITLE
chore: [BB-6436] Make a small change on help text for instructor

### PR DESCRIPTION
**Pull request by ngdangdat**
JIRA: N/A
**What changed?**
Add a small change on help text of a ORA setting to make it clearer to instructor

**Developer Checklist**

- [x] Reviewed the [release process](https://github.com/edx/edx-ora2/blob/master/.github/release_process.md)
- [x] Translations and JS/SASS compiled
- [ ] Bumped version number in [setup.py](https://github.com/edx/edx-ora2/blob/a62e81a9b0d89223476967ec3c27f3557a850735/setup.py#L39) and [package.json](https://github.com/edx/edx-ora2/blob/a62e81a9b0d89223476967ec3c27f3557a850735/package.json#L3)

**Testing Instructions**

- Checkout branch [open-craft:dat/BB-6436_push_instruction_to_ora_xblock](https://github.com/open-craft/edx-ora2/tree/dat/BB-6436_push_instruction_to_ora_xblock)
- Install edx-ora2 xblock on the feature branch to Studio (CMS)
- Restart CMS
- Add a ORA block in a unit
- Edit > Settings
- Make sure the changed text show up properly

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

**PoW**

Install modified version of xblock in Studio and the text is updated as expected

image

FYI: @openedx/content-aurora

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ngdangdat!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.




:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by Kelketek** [comment]
@natabene This MR is being done by @ngdangdat , who is a newcomer going through his trial period for OpenCraft. What is the procedure for the CLA in his case? Does this message count enough for attestation of affiliation or do we need to have him sign something in particular?

**Comment by tecoholic** [comment]
@ngdangdat :+1:

- [x] I tested this: Verified that the help text is updated in the Studio Edit window.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation - NA

Suggestion: The commit message is a little vague, can we make it more specific like "update the help text for Top Responses setting" or something similar?

**Comment by ngdangdat** [comment]
@tecoholic,

Thank you very much for your review and suggestion. I've updated the commit message following suggested one. Kindly check!

**Comment by natabene** [comment]
@ngdangdat Thank you for your contribution. Have you had a chance to fill out the request CLA form? Once that is done and processed, we will be able to review your code.

**Comment by Kelketek** [comment]
@natabene I pinged you on a comment above regarding the CLA, reposting here:

> This MR is being done by @ngdangdat , who is a newcomer going through his trial period for OpenCraft. What is the procedure for the CLA in his case? Does this message count enough for attestation of affiliation or do we need to have him sign something in particular?

**Comment by natabene** [comment]
@Kelketek Sorry, I missed that, thanks for bringing this to my attention. Please reach out to tCRIL for the proper way to handle this, as they govern the process of adding to the CLA list. Attestation here I am afraid won't be enough, but they will be able to tell you what would be sufficient.

**Comment by Kelketek** [comment]
Thanks, @natabene . @jmakowski1123 , what is the proper procedure here?

**Comment by tecoholic** [comment]
This is replaced with #1883.

**Comment by ngdangdat** [comment]
> This is replaced with #1883. Kindly close this and consider the other one for review.

I closed this one. Thank you, @tecoholic!

**Comment by tecoholic** [comment]
Thank you @ngdangdat

**Pull request closed without merging**
