### PR TITLE
FC-0001: update CourseWaffleFlag usage according to LegacyWaffle* de…

### PR DESCRIPTION
**Pull request by dyudyunov**
This is a part of https://github.com/openedx/public-engineering/issues/28

NOTE:
- this PR should be merged after the [related PR to the edx-platform](https://github.com/openedx/edx-platform/pull/30330)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov! I've created [OSPR-6645](https://openedx.atlassian.net/browse/OSPR-6645) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@dyudyunov Thank you for your contribution. Is this ready for our review?

**Review by robrap — COMMENTED** [review]
Could you updated the commit comment to something like:
```
refactor: update CourseWaffleFlag to FutureCourseWaffleFlag

This is a temporary step to get to a new version of CourseWaffleFlag.
This change must wait for edx-platform to first introduce the
FutureCourseWaffleFlag.
```

**Comment by dyudyunov** [comment]
> 

Done!)

**Review by robrap — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-ora2&entry.867055334=https://github.com/openedx/edx-ora2/pull/1853&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2022-04-28+12:41&entry.1917517419=2022-05-05+18:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by robrap** [comment]
The updated version has been released: https://pypi.org/project/ora2/4.3.0/

**Pull request merged**
