### PR TITLE
chore: remove bok-choy usage

### PR DESCRIPTION
**Pull request by salman2013**
Description

As the bok-choy has been deprecated https://github.com/openedx/public-engineering/issues/13, we are removing its usage from the code in this PR.

Ticket: https://github.com/orgs/openedx/projects/55/views/1?pane=issue&itemId=45415827

### CODE REVIEW

**Review by feanil — APPROVED** [review]
Change seems good to me.  @openedx/content-aurora when should we expect a review of this by?

**Comment by feanil** [comment]
@salman2013 should this still be in Draft?

**Comment by salman2013** [comment]
@feanil its ready for review.

**Comment by itsjeyd** [comment]
Hey @mattcarter, just a friendly reminder that this PR is ready for @openedx/2u-aurora to review.

**Pull request merged**
