### PR TITLE
feat: add ora filter for submission step rendering

### PR DESCRIPTION
**Pull request by BryanttV**
## Description
This PR triggers the ORA submission view filter. This filter changes the default template by a custom template with a warning message notifying the student that the Turnitin plagiarism check is enabled.

## Dependencies
This PR needs the new ORA submission view filter:
- https://github.com/openedx/openedx-filters/pull/158

## Supporting Information
These changes are based on those proposed in the [following ADR](https://github.com/openedx/edx-ora2/pull/2182)

## How to Test
Using **Tutor**:
1. Install this xblock with changes in this branch in the LMS/CMS services.
2. Install `openedx-filters` in the LMS/CMS services with [these changes](https://github.com/openedx/openedx-filters/pull/158).
3. Install `platform-plugin-turnitin` in the LMS/CMS services with the changes in the [ora filter branch](https://github.com/eduNEXT/platform-plugin-turnitin/tree/bav/ora-filter).
4. Add the Open edX Filters configuration to your environment and restart the services. You can use this inline plugin:

    ```yaml
    name: filters-settings
    version: 0.1.0
    patches:
      openedx-common-settings: |
        OPEN_EDX_FILTERS_CONFIG = {
          "org.openedx.learning.ora.submission_view.render.started.v1": {
            "fail_silently": False,
            "pipeline": [
              "platform_plugin_turnitin.extensions.filters.ORASubmissionViewTurnitinWarning",
            ]
          },
        }
    ```
5. In a unit of the course create a new ora assessment.
6. In the LMS, in the submission step (**1. Your Response**), you'll see:

    image

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @BryanttV! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by BryanttV** [comment]
Hi @pomegranited, this PR is part of the implementation of the [ADR for lightweight extension points](https://github.com/openedx/edx-ora2/pull/2182), could you take a look at it? Thanks!

**Review by mariajgrimaldi — APPROVED** [review]
This looks good! Although we're missing some tests, could we add some? Thanks!

**Comment by BryanttV** [comment]
Hi @mariajgrimaldi, thanks for the review! I added some tests: https://github.com/openedx/edx-ora2/commit/f4156f2a26af1199406867223f00d86f6d331769

**Review by pomegranited — APPROVED** [review]
:+1: Works great, thank you @BryanttV !

Could you merge latest `master` to get test passing again, and I'll merge :)

- [x] I tested this using the PR description, both with and without the added filters to ensure no errors.
- [x] I read through the code
- [x] I checked for accessibility issues by navigating with my keyboard.
- [x] Includes documentation
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

**Comment by openedx-webhooks** [comment]
@BryanttV 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-ora2&entry.867055334=https://github.com/openedx/edx-ora2/pull/2204&entry.1484655318=https://github.com/BryanttV&entry.752974735=2024-04-11+02:53&entry.1917517419=2024-04-18+01:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
